name: Extract Bertie

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  extract-bertie:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'merge_group' }}
    runs-on: linux

    steps:
      - name: ‚§µ Clone Bertie repository
        uses: actions/checkout@v4
        with:
          repository: cryspen/bertie

      - uses: actions/checkout@v4
        with:
          path: hax

      - if: runner.environment == 'github-hosted'
        uses: DeterminateSystems/nix-installer-action@main
        
      - name: ‚§µ Install hax
        run: |
          nix profile install ./hax

      - name: üèÉ Extract fstar
        run: ./hax-driver.py extract-fstar
